---
name: Build & Publish container
"on":
  push:
    branches: [main]

jobs:
  publish:
    uses: actionshub/reusable-workflows/.github/workflows/publish.yaml@cb64d61d896ad264d111c6d105a8e662f5e24210
